package Frontend;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

import Core.Statistics;

import javax.swing.*;
import java.io.File;

import static Core.Statistics.readStatistics;

/**
 *
 * @author emirm
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form newJava
     */
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null);

        Statistics stats = readStatistics();
        try {
            if(stats != null) {
                lblCompleteds.setText(String.valueOf(stats.getVictory()));
                lblFaileds.setText(String.valueOf(stats.getLosses()));
                lblUnfinisheds.setText(String.valueOf(stats.getUnfinishedGames()));
                lblAttemps.setText(String.valueOf(String.format("%.2f", stats.getAvgFinishAtLines())));
                lblTime.setText(String.valueOf(stats.getAvgSuccessTime()));
            }else{
                lblCompleteds.setText("-");
                lblFaileds.setText("-");
                lblUnfinisheds.setText("-");
                lblAttemps.setText("-");
                lblTime.setText("-");
            }
            File f = new File("SavedGame.dat");
            if (!f.exists()){
                btnContinue.setVisible(false);
            }
        }catch (Exception e){

        }



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNGamesCompleted = new javax.swing.JLabel();
        lblNFailed = new javax.swing.JLabel();
        lblNUnfinished = new javax.swing.JLabel();
        lblNAvgTime = new javax.swing.JLabel();
        lblNAvgAttemp = new javax.swing.JLabel();
        lblCompleteds = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblFaileds = new javax.swing.JLabel();
        lblAttemps = new javax.swing.JLabel();
        lblUnfinisheds = new javax.swing.JLabel();

        jLabel8.setText("-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Oswald SemiBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NERDLE");

        btnNewGame.setText("New Game");
        btnNewGame.setActionCommand("");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        btnTest.setText("UnitTest");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        jLabel2.setText("5 - 20011103 Mehmet Keçeci - 20011062 Emir Çağrı Aykın");

        lblNGamesCompleted.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNGamesCompleted.setText("Succesfull Games");

        lblNFailed.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNFailed.setText("Failed Games");

        lblNUnfinished.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNUnfinished.setText("Unfinished Saved Games");

        lblNAvgTime.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNAvgTime.setText("Average Succeed Time (s)");

        lblNAvgAttemp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNAvgAttemp.setText("Average Succeed  Attemps");

        lblCompleteds.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCompleteds.setForeground(new java.awt.Color(0, 153, 0));
        lblCompleteds.setText("null");

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 153, 0));
        lblTime.setText("null");

        lblFaileds.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFaileds.setForeground(new java.awt.Color(204, 0, 0));
        lblFaileds.setText("null");

        lblAttemps.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAttemps.setForeground(new java.awt.Color(0, 153, 0));
        lblAttemps.setText("null");

        lblUnfinisheds.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUnfinisheds.setForeground(new java.awt.Color(204, 204, 0));
        lblUnfinisheds.setText("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(248, 248, 248)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(77, 77, 77)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblNFailed)
                                                                        .addComponent(lblNUnfinished)
                                                                        .addComponent(lblNAvgTime)
                                                                        .addComponent(lblNAvgAttemp))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblTime)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(lblCompleteds)
                                                                                        .addComponent(lblUnfinisheds, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(lblFaileds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(lblAttemps)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblNGamesCompleted)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(52, 52, 52)))
                                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblNGamesCompleted)
                                                        .addComponent(lblCompleteds))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblUnfinisheds, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblNUnfinished))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(lblNFailed)
                                                                        .addComponent(lblFaileds, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblNAvgTime))
                                                        .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblAttemps, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblNAvgAttemp))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {
       // NewGame newGame = new NewGame();
        File file = new File("SavedGame.dat");
        if(file.exists()){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (this, "Your saved game will be deleted. Are you sure you want to start a new game?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                file.delete();
                NewGame newGame = new NewGame();
                this.dispose();
            }
        }else{
            NewGame newGame = new NewGame();
            this.dispose();
        }

    }

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {
        Continue aContinue = new Continue();

        this.dispose();
    }

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {
        TestPage testPage = new TestPage();
        testPage.setVisible(true);

        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAttemps;
    private javax.swing.JLabel lblCompleteds;
    private javax.swing.JLabel lblFaileds;
    private javax.swing.JLabel lblNAvgAttemp;
    private javax.swing.JLabel lblNAvgTime;
    private javax.swing.JLabel lblNFailed;
    private javax.swing.JLabel lblNGamesCompleted;
    private javax.swing.JLabel lblNUnfinished;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUnfinisheds;
    // End of variables declaration
}
